name: legal-gui
channels:
  - conda-forge
dependencies:
  # Python version
  - python=3.10

  # RDKit (chemoinformatics)
  - rdkit=2023.09.3

  # Dash et extensions
  - pip
  - pip:
      - dash>=2.16.1
      - dash-bootstrap-components>=1.6.0

  # Utilitaires
  - pandas
  - numpy
  - diskcache         # pour callbacks longs ou caching disque
  - flask
  - plotly
